### ISSUE TITLE
The cursor is directly positioned after the arrow

### ISSUE THREAD

**Issue by Cameo007** [gTerminal-project/gTerminal-project.github.io#1]
... a margin would be good as for the text, which is positioned correctly.

**Comment by J0J0HA** [comment]
This issue is only in chromium based browsers, and happens because the space after the &gt; is a normal space. It would be fixed by using a &ndsp;.

I will fix this now.

**Comment by Cameo007** [comment]
It is not working.

**Comment by J0J0HA** [comment]
The issue should now be fixed.
